### PR TITLE
Migrate to intellij-platform-gradle-plugin v2.0.0

### LINKED ISSUE #11: Support intellij-platform-gradle-plugin 2.0.0-rc
Hi!

[IntelliJ Platform Gradle Plugin](https://github.com/JetBrains/intellij-platform-gradle-plugin) has been moving really quickly as a result of fantastic work by @hsz (seriously, the Developer Experience is now much nicer!).

One great feature of the upcoming 2.0.0 release that would be super handy for this plugin is there is now much better experience when developing for multiple IDEs, which this plugin will have to accomodate for, eg IDEA, PyCharm, GoLand and the million other IDEs JetBrains now has, which would help with testing specific IDEs.

The good thing is that it's fairly straight forward to migrate (I've moved a couple of plugins, some small.. one rather larger), let me know if you want me to contribute this change.

It should hopefully be a version bump in [libs.versions.toml](https://github.com/134130/intellij-mise/blob/refs/heads/main/gradle/libs.versions.toml), [gradle.properties](https://github.com/134130/intellij-mise/blob/refs/heads/main/gradle.properties), then updating [build.gradle.kts](https://github.com/134130/intellij-mise/blob/refs/heads/main/build.gradle.kts) with the new syntax.

[Docs](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html)
[Migration to 2.0](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html)

### PR DESCRIPTION
**Pull request by 134130**
## Description
- Migrate to intellij-platform-gradle-plugin v2.0.0
- Closes #11

### CODE REVIEW

**Comment by 134130** [comment]
@joshuataylor Did I do it right?

**Comment by joshuataylor** [comment]
I'll give a test on both PyCharm Community and pro and let you know!

Thanks! Half the issue with IntelliJ plugins is figuring out how everything fits together. 🙃

**Comment by joshuataylor** [comment]
Last comment was for the wrong issue, I'll test and let you know.

**Comment by joshuataylor** [comment]
Use `org.jetbrains.intellij.platform.module` for the subprojects. This is a new feature so you don't need to do the `gradle.taskGraph.whenReady(` part.

It is basically a subplugin - see https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#multi-module-project-structure

and

https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#plugins

**Comment by joshuataylor** [comment]
Might be worth creating a CONTRIBUTING.md with tips about launching the IDEs (which honestly for me is usually when I forget something about a project :-))

I also wrote a bash script I quickly made which will add each supported IDE to .run in the same way the `Run Plugin` task is done.

Both my notes about contributing and runIde are here: https://gist.github.com/joshuataylor/8ed59c23f89756cf095ba3533fadc2aa

(will probably use both for other projects, it's super handy)

**Comment by 134130** [comment]
> Use `org.jetbrains.intellij.platform.module` for the subprojects. This is a new feature so you don't need to do the `gradle.taskGraph.whenReady(` part.
> 
> It is basically a subplugin - see [plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#multi-module-project-structure](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#multi-module-project-structure)
> 
> and
> 
> [plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#plugins](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#plugins)

It looks so nice!!

**Comment by 134130** [comment]
> Might be worth creating a CONTRIBUTING.md with tips about launching the IDEs (which honestly for me is usually when I forget something about a project :-))
> 
> I also wrote a bash script I quickly made which will add each supported IDE to .run in the same way the `Run Plugin` task is done.
> 
> Both my notes about contributing and runIde are here: [gist.github.com/joshuataylor/8ed59c23f89756cf095ba3533fadc2aa](https://gist.github.com/joshuataylor/8ed59c23f89756cf095ba3533fadc2aa)
> 
> (will probably use both for other projects, it's super handy)

Thanks! For your information, intellij-gradle-plugin-platform v2 introduces [intellijPlatformTesting](https://blog.jetbrains.com/platform/2024/07/intellij-platform-gradle-plugin-2-0/#improved-testing-experience), which makes no bash scripts for making test configuration.

**Comment by joshuataylor** [comment]
Thanks!! Was looking for that this morning through the docs, knew I saw it somewhere.

**Pull request merged**
